# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Black Girls Code - Johannesburg
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  image. build. create.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bgc-jhb.github.io" # the base hostname & protocol for your site
github_username: bgc-jhb
twitter_username:
facebook_name: BlackGirlsCodeJohannesburg

# Build settings
markdown: kramdown
